Add ServiceManager
apmath-web/template-kotlin pull request #10
Opened 2019-04-16 21:42 UTC by BarracudaPff

Using lightweight DI for Kotlin and Ktor - [Koin](https://github.com/InsertKoinIO/koin)
- [x] Add [Koin](https://github.com/InsertKoinIO/koin) dependency
- [x] Create `ServiceManager`
- [x] Implement Koin into Ktor
- [x] Add documentation
- [x] Add example

2019-04-17 18:30 UTC, malinink commented
зкщvide issue link on top

2019-04-17 18:53 UTC, malinink requested changes
Давайте напишу на русском как лучше сделать.
У коина парадигма немного другая, и запиливать SM тут нет большого смысла.

Давайте сделаем следующее. Добавим модуль в инфраструктуру, тот в котором зависимости.
И предлагаю непосредственно в экшенах использовать сервисы в формате:
`val service: HelloService by inject()`

Модуль назовем текущим именем приложения(template напрмиер), скорее всего для ряда тестов будет необходимость подключать другой модуль, я этого не исключаю.

Cоответственно безо всяких SM.

https://insert-koin.io/docs/2.0/getting-started/ktor/

2019-04-17 18:53 UTC, malinink commented on src/domain/posts/PostsService.kt
> -package com.apmath.template.domain.posts
Very strange manipulations, how it is possible that you remove file and after that add it again?
Why do you do things like that?

2019-04-17 18:54 UTC, malinink requested changes

2019-04-17 18:54 UTC, malinink commented on gradle.properties
> +koin_version=2.0.0-rc-1
rc-2 is newest one

2019-04-17 19:35 UTC, BarracudaPff commented on src/domain/posts/PostsService.kt
> -package com.apmath.template.domain.posts
Это все из-за отсутствия пакетов как папок, IDEA ломается. Если просто перемещать пакеты - все крашится. Пришлось копировать и удалять

2019-04-17 19:39 UTC, BarracudaPff commented on src/com/apmath/template/application/v1/actions/Post.kt
> +suspend fun ApplicationCall.v1Post(route: Route) {
Есть такой вариант.
`inject` просто так не вызвать, это нужно делать из под `Application` или `Route`

2019-04-18 06:02 UTC, malinink commented on src/com/apmath/template/application/v1/actions/Post.kt
> +suspend fun ApplicationCall.v1Post(route: Route) {
Мне кажется, что самым нормальным вариантом может быть такой:

- На уровне `Api.kt` для каждого отдельно взятого роута, мы определяем свои конкретные зависимости и передаем их в `call.v1Post(~dependencies~)`

Таким образом:
- В экшенах уже DI нет, они получили всё что хотели.
- У нас нет тонны сервисов в `Application.kt`.
- Всю рутину DI делает `koin`
- А зависимости явно передаются в роутинге.

2019-04-18 20:04 UTC, malinink approved these changes

2019-04-18 20:04 UTC, merged